import 'package:hive_flutter/hive_flutter.dart';
import '../../core/models/content_models.dart';

class HiveService {
  static const String _progressBox = 'user_progress';
  static const String _settingsBox = 'app_settings';
  static const String _progressKey = 'progress';
  static const String _settingsKey = 'settings';

  static Future<void> init() async {
    await Hive.initFlutter();

    // Register all adapters (generated by build_runner)
    Hive.registerAdapter(SubjectAdapter());
    Hive.registerAdapter(ModuleAdapter());
    Hive.registerAdapter(ChapterAdapter());
    Hive.registerAdapter(LessonAdapter());
    Hive.registerAdapter(LessonBlockAdapter());
    Hive.registerAdapter(UserProgressAdapter());
    Hive.registerAdapter(LessonProgressAdapter());
    Hive.registerAdapter(ChapterProgressAdapter());
    Hive.registerAdapter(ModuleProgressAdapter());
    Hive.registerAdapter(AppSettingsAdapter());

    await Hive.openBox<UserProgress>(_progressBox);
    await Hive.openBox<AppSettings>(_settingsBox);
  }

  // ─── Progress ─────────────────────────────────────────────

  static Box<UserProgress> get _pb => Hive.box<UserProgress>(_progressBox);

  static UserProgress getOrCreateProgress() {
    final existing = _pb.get(_progressKey);
    if (existing != null) return existing;
    final progress = UserProgress(userId: 'guest');
    _pb.put(_progressKey, progress);
    return progress;
  }

  static Future<void> saveProgress(UserProgress progress) async {
    await _pb.put(_progressKey, progress);
  }

  static Future<void> completeLesson({
    required String lessonId,
    required String chapterId,
    required String moduleId,
    required int totalLessonsInChapter,
    required int totalChaptersInModule,
    required int accuracyPercent,
  }) async {
    final progress = getOrCreateProgress();
    final now = DateTime.now();

    // ── Streak logic ──
    final last = progress.lastActiveDate;
    if (last != null) {
      final diff = now.difference(last).inDays;
      if (diff == 1) {
        progress.currentStreakDays++;
      } else if (diff > 1) {
        progress.currentStreakDays = 1;
      }
    } else {
      progress.currentStreakDays = 1;
    }
    progress.lastActiveDate = now;

    // ── Lesson ──
    if (!(progress.lessonProgress[lessonId]?.isCompleted ?? false)) {
      progress.lessonProgress[lessonId] = LessonProgress(
        lessonId: lessonId,
        isCompleted: true,
        starsEarned: 1,
        xpEarned: 50,
        completedAt: now,
        bestAccuracyPercent: accuracyPercent,
      );
      progress.totalStars += 1;
      progress.totalXp += 50;
    } else {
      // Update best accuracy
      final lp = progress.lessonProgress[lessonId]!;
      if (accuracyPercent > lp.bestAccuracyPercent) {
        lp.bestAccuracyPercent = accuracyPercent;
      }
    }

    // ── Chapter ──
    final cp = progress.chapterProgress[chapterId] ??
        ChapterProgress(
          chapterId: chapterId,
          totalLessons: totalLessonsInChapter,
        );
    cp.completedLessons = progress.lessonProgress.values
        .where((lp) => lp.isCompleted)
        .length; // recalculate
    if (!cp.isCompleted && cp.completedLessons >= totalLessonsInChapter) {
      cp.isCompleted = true;
      cp.starsEarned = 5;
      progress.totalStars += 5;
      progress.totalXp += 100;
    }
    progress.chapterProgress[chapterId] = cp;

    // ── Module ──
    final mp = progress.moduleProgress[moduleId] ??
        ModuleProgress(
          moduleId: moduleId,
          totalChapters: totalChaptersInModule,
        );
    mp.completedChapters = progress.chapterProgress.values
        .where((c) => c.isCompleted)
        .length;
    if (!mp.isCompleted && mp.completedChapters >= totalChaptersInModule) {
      mp.isCompleted = true;
      mp.starsEarned = 10;
      progress.totalStars += 10;
      progress.totalXp += 200;
    }
    progress.moduleProgress[moduleId] = mp;

    // ── Level up ──
    while (progress.totalXp >= progress.xpForNextLevel) {
      progress.level++;
    }

    await saveProgress(progress);
  }

  // ─── Settings ─────────────────────────────────────────────

  static Box<AppSettings> get _sb => Hive.box<AppSettings>(_settingsBox);

  static AppSettings getOrCreateSettings() {
    final existing = _sb.get(_settingsKey);
    if (existing != null) return existing;
    final settings = AppSettings();
    _sb.put(_settingsKey, settings);
    return settings;
  }

  static Future<void> saveSettings(AppSettings settings) async {
    await _sb.put(_settingsKey, settings);
  }

  static Future<void> toggleDarkMode(bool value) async {
    final s = getOrCreateSettings();
    s.isDarkMode = value;
    await saveSettings(s);
  }
}
